#!/usr/bin/env bash
# This script displays "Best School" 10 times, but on the 9th iteration it displays "Best School" followed by "Hi" on a new line

counter=1

while [ $counter -le 10 ]; do
    echo "Best School"
    
    if [ $counter -eq 9 ]; then
        echo "Hi"
    fi
    
    counter=$((counter + 1))
done
